### ISSUE TITLE
General question about the repo

### ISSUE THREAD

**Issue by GraSkill** [anapiashko/flip#2]
Hi @anapiashko how is your week going?
I hope I can the question here in the issue ;)

1. Did you build the repo from scratch? Or did you copy/clone/fork it from any other repo?
2. What's your a level of all the tech stacked used  here? GitHubActions, Docker, Kube, Mvn, Java, etc.
3. The link do not work, can I run it locally? Can you add a description how to do it locally?

Thanks, have a nice day.
Gra

**Comment by GraSkill** [comment]
For that part please check the invite section, and contact your vendor.
I don't want to share that information here. It's about meeting on Friday.

**Comment by anapiashko** [comment]
Okay, I got your point, then please find my answers below:
1. I built the repo from scratch
2. I would say confident usage of listed technologies, but k8s is something new for me
3. Yes, recently heroku restricted free deployments, but you still can run the project with _docker-compose.yml_ that is in the root of the project 

Thanks,
Anastasiya

**Comment by GraSkill** [comment]
@anapiashko  TY, can U do the new project from invite - private, and we can discuss more in the project issues, TY.
The questions I'm asked, is not the most important once. I like Ur repos, that's why I'm asked the questions.

**Comment by anapiashko** [comment]
Thanks for reviews!
I forked the provided repo as private

**Comment by GraSkill** [comment]
yes, please add me there.

**Comment by GraSkill** [comment]
I cannot create an issue

**Comment by GraSkill** [comment]
TY works fine now
